/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router
// Do not edit this file manually.
// Run `vite` (or `vite build`) to regenerate.
import { Route as rootRoute } from './routes/__root'
import { Route as IndexLazyImport } from './routes/index.lazy'
import { Route as AboutLazyImport } from './routes/about.lazy'

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

export interface FileRoutesByPath {
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof IndexLazyImport
    parentRoute: typeof rootRoute
  }
  '/about': {
    id: '/about'
    path: '/about'
    fullPath: '/about'
    preLoaderRoute: typeof AboutLazyImport
    parentRoute: typeof rootRoute
  }
}

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutLazyRoute,
})
/* prettier-ignore-end */
