/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const CalculateurLazyRouteImport = createFileRoute('/calculateur')()
const IndexLazyRouteImport = createFileRoute('/')()

const CalculateurLazyRoute = CalculateurLazyRouteImport.update({
  id: '/calculateur',
  path: '/calculateur',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/calculateur.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/calculateur': typeof CalculateurLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/calculateur': typeof CalculateurLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/calculateur': typeof CalculateurLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calculateur'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calculateur'
  id: '__root__' | '/' | '/calculateur'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CalculateurLazyRoute: typeof CalculateurLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calculateur': {
      id: '/calculateur'
      path: '/calculateur'
      fullPath: '/calculateur'
      preLoaderRoute: typeof CalculateurLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CalculateurLazyRoute: CalculateurLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
